[app]
name = "webapp"
port = 8080

[log]
level = "debug"

[mysql]
host = "127.0.0.1"
port = 3306
user = "username"
password = "password"
database = "database"

[redis]
host = "127.0.0.1"
port = 6379
database = 0
password = "password"
